# Generated by Django 2.2.6 on 2019-10-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('main', models.BooleanField(default=False)),
                ('subclasses', models.ManyToManyField(blank=True, related_name='_classification_subclasses_+', to='classifier.Classification')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='uploads')),
                ('time_classified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField()),
                ('analysis', models.TextField(blank=True)),
                ('main_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.Classification')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Source')),
                ('sub_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columns', to='classifier.Classification')),
            ],
            options={
                'unique_together': {('source', 'index')},
            },
        ),
    ]
